apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: c-sharp-azure-gh 
  janus-idp.io/tekton: c-sharp-azure-gh
  backstage.io/kubernetes-id: c-sharp-azure-gh
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: c-sharp-azure-gh
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml