apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: c-sharp-azure-gh-gitops
  description: This is GitOps manifest for c-sharp-azure-gh   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=c-sharp-azure-gh
    backstage.io/kubernetes-id: c-sharp-azure-gh 
    backstage.io/techdocs-ref: dir:.
    dev.azure.com/project-repo: lucarval-rhtap/c-sharp-azure-gh-gitops
    dev.azure.com/project: shared-public
    dev.azure.com/build-definition: lucarval-rhtap.c-sharp-azure-gh-gitops
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:c-sharp-azure-gh
